### PR TITLE
Fixed Incorrect Params and Optimisation

### PR DESCRIPTION
**Pull request by DonHulieo**
Fixes Typos and incorrect params in my latest PR, finish off my PR from 8 months ago, localise QBCore and PlayerJob, added new config options for Player Jobs with new functions for checking duty and added variables to base alerts to reduce Native load.

### CODE REVIEW

**Comment by DonHulieo** [comment]
Before submitting this PR for review, there's a number of alerts that could be automated using ShockingEvents. The list is as follows;

- InjuriedPerson
- DeceasedPerson
- OfficerDown
- EmsDown
- SuspiciousActivity

Is it worth having any of these automated and set up on a timer?

**Comment by MonkeyWhisper** [comment]
Hi @DonHulieo, thanks for the PR.

This branch of yours have been tested on a live environment?

**Comment by DonHulieo** [comment]
Hello, it has been on a semi-live environment, (me and one or two other devs) but not for the sole purpose of testing this scripts functionality. 
I can happily arrange that however, especially if it saves your team some precious time during what seems a heavy development cycle! :)

**Comment by DonHulieo** [comment]
> 

I will note though, through testing I've removed any errors I've had on my end and made significant performance increases by changing the how the client loop worked. I'll do some rigorous testing over the next couple days and report back.

**Comment by MonkeyWhisper** [comment]
> 

Thank you very much, are those improvements parts of this PR and any errors fixed?

**Comment by DonHulieo** [comment]
> 

Yea all improvements are already in this PR, and all found errors (to the best of my knowledge) are eradicated.

**Comment by DonHulieo** [comment]
So after speaking with a friend, this has been used in a live environment, and has only returned one issue. 
Automatic Speeding Vehicle Events don't seem to be firing, and I'm working on a fix as we speak, but other than that, no found errors.

**Comment by DonHulieo** [comment]
Had a slight mishap in the commit, but all known issues with this PR have now been rectified.

**Comment by DonHulieo** [comment]
I'll resolve conflicts with latest commit and re pull request.

**Pull request closed without merging**
