### PR TITLE
tooltips for dispatch menu

### PR DESCRIPTION
**Pull request by lenzh**
only the locales needs to be put in but no idea tbh locales are made in en.json

### CODE REVIEW

**Comment by lenzh** [comment]
image

**Comment by S1lentcodes** [comment]
Hey thanks for the PR, I think we can go about doing tooltips with a different approach, I will push the code up when I get time for you to see.

**Comment by LeSiiN** [comment]
Is there a update on this? @S1lentcodes

**Comment by MonkeyWhisper** [comment]
Closing PR

**Comment by MonkeyWhisper** [comment]
Ops, sorry, I didn't meant to close it

Branch already has conflicts

**Comment by LeSiiN** [comment]
> Ops, sorry, I didn't meant to close it
> 
> Branch already has conflicts

Yeah, its very old

**Pull request closed without merging**
