### PR TITLE
Add cs locale

### PR DESCRIPTION
**Pull request by zdenda142**

### CODE REVIEW

**Comment by LeSiiN** [comment]
Please add a new row inside the readme for ( supported languages ), also please add the 2 missing locales, can be found in my PR https://github.com/Project-Sloth/ps-dispatch/pull/172/commits/29273ef86d3f0d107bf0a6d3be367bde6f4e216d

**Comment by LeSiiN** [comment]
Missing locales for these 2 https://github.com/Project-Sloth/ps-dispatch/commit/29273ef86d3f0d107bf0a6d3be367bde6f4e216d , then its all good

**Review by LeSiiN — APPROVED** [review]
just needs to be checked by anybody that can speak czech then it can be merged

**Comment by zdenda142** [comment]
> just needs to be checked by anybody that can speak czech then it can be merged

It was translated by my friend and I checked it after him and everything is fine

**Pull request merged**
