### PR TITLE
Update locales.lua add cs translate

### PR DESCRIPTION
**Pull request by zdenda142**

### CODE REVIEW

**Comment by zdenda142** [comment]
Why close

**Comment by xFutte** [comment]
> Why close

Good question. @OK1ez ?

**Comment by OK1ez** [comment]
ps-dispatch v2 is around the corner and will be using a new locale system

**Comment by xFutte** [comment]
> ps-dispatch v2 is around the corner and will be using a new locale system

Not everyone might want to update to the next version right away, if they have added custom code. I don't see a reason why it should not be added.

**Pull request closed without merging**
