### PR TITLE
MultiDepartment Support, AutoAlert Fixes & Improvements and Optimisation

### PR DESCRIPTION
**Pull request by DonHulieo**
Hey, just a resubmit my recent PR, including all recent changes :) .

Written and Tested on Stream;
(stream crashed but I test in the last stream)
https://www.twitch.tv/videos/1759965124

Client Changes;
- Added multidepartment support for all EMS jobs.
- Increased Sleep to 1000 (1sec) in cl_loops.lua to decrease resmon.
- Moved Hunting Zones Circle Zone to a Chunk in cl_main.lua (removing the thread).
- Moved Blip Creation and Deletion (for Hunting Zones) to PlayerLoaded and PlayerUnload Events Respectively.
- Changed Global isLoggenIn to LocalPlayer.state.isLoggedIn.
- Added More Vehicle Events so Speeding Alerts are Consistent.
- Added Checks for Melee Calls to ensure there are Witnesses (reduce spam and immersion).
- Added Auto CarJacking and VehicleTheft, that trigger on Two Scenarios Respectively;
  - If a Player is Attempting to Removed a Ped from a Vehicle
  - & If a Player sets off the Cars Alarm
- Include Hunting Zone Checks for Changes and Make Auto Shooting Alerts Work Again

Server Changes;
- Added multidepartment support for all EMS jobs.

Shared (Config) Changes;
- Added Config Options for Different Police & other EMS jobs.
- Removed the Citizen.CreateThread in favour of a Chunk Compiled at StartUp.
- Changed Sleep Times to reflect changes in cl_loops.lua.

### CODE REVIEW

**Comment by LeSiiN** [comment]
Nice Edits for my Hunting Zones, love it

**Comment by DonHulieo** [comment]
> Nice Edits for my Hunting Zones, love it

Thank you, a few tricks I learnt recently with PolyZone :)
Great PR on the zones, they’ve been a long time coming!

**Comment by LeSiiN** [comment]
Absolutely, glad i got it to work.

**Comment by BackSH00TER** [comment]
Nice job. I like the use of all the native events rather than writing all sorts of non-performant custom threads.

**Comment by DonHulieo** [comment]
> Nice job. I like the use of all the native events rather than writing all sorts of non-performant custom threads.

It's definitely something that can be applied to alot of resources to help with performance. I'm glad I took the time to research and find them, as they've already helped  my own resources immensely!

**Comment by MonkeyWhisper** [comment]
Great job, thanks for the PR!

**Comment by DonHulieo** [comment]
> Great job, thanks for the PR!

Thank you!

**Pull request merged**
