### PR TITLE
fix for radius not removing

### PR DESCRIPTION
**Pull request by LeSiiN**
- cleardispatchblips command should remove radius aswell
- Remove Blip inside MDT should remove radius aswell

Preview:
https://www.youtube.com/watch?v=REFUSAe9BDs

### CODE REVIEW

**Review by Veolene — CHANGES_REQUESTED** [review]
As stated in #117:

Whenever you have a blip without a radius, variable radius2 will stay empty and will output a script error everytime it gets called. There needs to be a check if variable radius is being used or not.

It's an absolute good PR, so I appreciate swift assistance in this issue already <3

**Comment by LeSiiN** [comment]
So i tryed to replicate ur issue on my end.
https://www.youtube.com/watch?v=TV1qDKZ8EA8

**Comment by Veolene** [comment]
I see! I am going to get a clean install of ps-dispatch then, thank you!

**Review by Veolene — APPROVED** [review]
👍

**Comment by MonkeyWhisper** [comment]
> 👍

What did you approve exactly? I don't see any testing or comments left?

**Pull request merged**
