### PR TITLE
Police shooting fix + setdispatchgps keymapping

### PR DESCRIPTION
**Pull request by AnishBplayz**
- Fixed a issue where police got dispatch calls when they shot bullets from their weapons

- Added DispatchGPS keymapping, pressing 'Y' when you get a dispatch call marks the waypoint on your map

### CODE REVIEW

**Comment by AnishBplayz** [comment]
Had to make a new PR as some of my edits where added in from PR of Viper's.

**Review by D40G — APPROVED** [review]
tested on production. Good to go

**Comment by AnishBplayz** [comment]
Enabled lua54 on the script and added ``QBCore export`` to ``cl_commands, cl_events, cl_extraalerts`` as they started making issues recently on fresh qbcore and existing ones too.

**Review by GhostV-Survival — APPROVED** [review]
works fine

**Review by Twikii — COMMENTED** [review]
Working smoothly

**Review by Twikii — APPROVED** [review]

**Comment by AnishBplayz** [comment]
Closing this PR as there's a better one by DonHuelio

**Pull request closed without merging**
