### PR TITLE
lets it save after server restart or rejoin

### PR DESCRIPTION
**Pull request by LeSiiN**
lets it save after server restart or rejoin

### CODE REVIEW

**Comment by RazerGhost** [comment]
Works just as intended by saving the last position of the dispatch for the user: https://youtu.be/MxlG5FlegmM

**Review by MonkeyWhisper — CHANGES_REQUESTED** [review]
Not aligned
image

**Comment by RazerGhost** [comment]
I dont think it ever was aligned, this is latests release
image

**Comment by LeSiiN** [comment]
> I dont think it ever was aligned, this is latests release image

i would edit the top line to a darker black then the infos below ;) image

**Comment by RazerGhost** [comment]
Thanks for the suggestion. Will definitely do that, never thought about changing it haha

> > I dont think it ever was aligned, this is latests release image
> 
> i would edit the top line to a darker black then the infos below ;) image

**Pull request merged**
