### PR TITLE
Remove Client Loops For Handlers

### PR DESCRIPTION
**Pull request by DonHulieo**
Removed the need for loops on the client for checking speed, gunshots and melee attacks.

Still in testing, currently gunshots definitely return alerts consistently, will post here as most alerts are confirmed.

### CODE REVIEW

**Comment by DonHulieo** [comment]
Fully tested, left only the timer in Cl_loops.lua but all handler and their respective alerts seem fully functional.

**Comment by AnishBplayz** [comment]
does the speed, gunshots and melee attacks alert show even to police when they do it ?

**Comment by AnishBplayz** [comment]
I just tested and checked out the whole code..... **isPlayerWhitelisted** isn't even a value in the whole script.... can you look into that too ?

**Comment by DonHulieo** [comment]
> I just tested and checked out the whole code..... **isPlayerWhitelisted** isn't even a value in the whole script.... can you look into that too ?

So when I was writing that, it confused me too. isPlayerWhitelisted is undefined in the original code and is just a nil variable. 
To stop police triggering alerts, Config.Debug needs to be false, like with the original code. I'll remove this variable and update?

**Comment by AnishBplayz** [comment]
i see there is this function which isn't used in the original code
image

So what if we add 
`local isPlayerWhitelisted = refreshPlayerWhitelisted()`

In the client/cl_eventhandlers ?

I was trying this out now will let you know the result....

**Comment by DonHulieo** [comment]
Wouldn't we be better using this?
`function IsPoliceJob(job)
    for k, v in pairs(Config.PoliceJob) do
        if job == v then
            return true
        end
    end
    return false
end`
As it will stop alerts for all configured policejobs?

**Comment by AnishBplayz** [comment]
yup we can i will test it our rn

**Comment by DonHulieo** [comment]
From my testing seems to work fine, no alerts if Config.Debug is false and the player is a police officer!

**Review by darktrovx — APPROVED** [review]

**Comment by DonHulieo** [comment]
little bit of a github noob here, it's asking me to sign the commits but I'm a bit lost as to how or what its asking?

I thought they were already signed, or is it not something on my end?

**Review by AnishBplayz — APPROVED** [review]

**Comment by AnishBplayz** [comment]
image

PlayerJob value is not defined

**Comment by DonHulieo** [comment]
This indicates something else is wrong surely? As I didn't touch the PlayerJob functions. It's defined when the Player Loads and the JobUpdate event fires.

**Comment by AnishBplayz** [comment]
> This indicates something else is wrong surely? As I didn't touch the PlayerJob functions. It's defined when the Player Loads and the JobUpdate event fires.

All Good it was my issue I localised the PlayerJob Variable earlier.... fixed it

**Comment by DonHulieo** [comment]
I have more updates on a dev branch, mostly optimisation, clearing up some PRs and finishing my PR from 8 months ago. Should I just push these for review, or wait until this PR is merged?

**Pull request merged**
