### PR TITLE
Fix Duty issue

### PR DESCRIPTION
**Pull request by imgucciwz**
This fixes the duty issue where sometimes the duty doesn't get updates.

### CODE REVIEW

**Comment by ChickenDipper1** [comment]
Tested and works fine, a very annoying bug I had happening a lot. Was causing off duty ems and police to receive alert sounds with no on screen notifications till I changed this.

**Review by ChickenDipper1 — APPROVED** [review]
Works as expected, stops off duty staff getting alert sounds still also.

**Review by StyrpexRoleplay — COMMENTED** [review]
Thank you so much! Workly perfect!

**Review by StyrpexRoleplay — APPROVED** [review]
Work perfect!

**Review by MonkeyWhisper — APPROVED** [review]

**Pull request merged**
