### PR TITLE
Improve Version Check

### PR DESCRIPTION
**Pull request by DonHulieo**
Moved to using promise API for resloving the GitHub data, also using pure numerical evaluation of versions for better performance.

Also fixed the null function string.strsplit, using string.gsub.

Renamed to sv_versioncheck and bumped version.

### CODE REVIEW

**Comment by xFutte** [comment]
I've made a core export for this. If we go with that or this version, this should be moved into core instead.

**Comment by DonHulieo** [comment]
> I've made a core export for this. If we go with that or this version, this should be moved into core instead.

No worries, is there much functional difference between this function and your export?

**Comment by xFutte** [comment]
> > I've made a core export for this. If we go with that or this version, this should be moved into core instead.
> 
> No worries, is there much functional difference between this function and your export?

My version has some more checks an approaches the way of getting the repository link a different way. My version takes the resource as a parameter instead of the GitHub repository.

**Comment by DonHulieo** [comment]
> > > I've made a core export for this. If we go with that or this version, this should be moved into core instead.
> > 
> > 
> > No worries, is there much functional difference between this function and your export?
> 
> My version has some more checks an approaches the way of getting the repository link a different way. My version takes the resource as a parameter instead of the GitHub repository.

Ah so more of an anonymous function, wouldn't be hard to change this one to be similar as well, would love to see you work.
Whatever we go with, I don't mind :) .

**Comment by xFutte** [comment]
Exactly. I'll close this PR for now and then we can go over what I've made (eventually stream on Discord).

**Pull request closed without merging**
