### PR TITLE
Refactored menu loop for better performance

### PR DESCRIPTION
**Pull request by xFutte**
Possible fix for #216

### CODE REVIEW

**Comment by Gnavling** [comment]
Seems to be an improvement so far. I'll see if the delay builds up as the calls start to populate.

**Comment by xFutte** [comment]
> Seems to be an improvement so far. I'll see if the delay builds up as the calls start to populate.

Sounds good. Will merge ASAP.

**Comment by Gnavling** [comment]
Delay does definitely still build up. After around 45 minutes of testing, I'm at about a 3-second delay for opening the MDT.

**Comment by Gnavling** [comment]
Would profilers or anything be helpful for you?

**Comment by MonkeyWhisper** [comment]
> Possible fix for #216

Will test and advise

**Comment by xFutte** [comment]
> Would profilers or anything be helpful for you?

A screenshot of the amount of HTML elements that has been loaded into the DOM over time would be helpful. One after like 3 minutes and then one after 10 minutes.

**Comment by xFutte** [comment]
@Gnavling Is it only the MDT that gets slow, or is it all NUIs?

**Pull request merged**
